name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      # Шаг 3: Переход в папку my-resume
      - name: Change directory
        working-directory: ./my-resume
        run: |
          echo "Working in my-resume directory"

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: |
          bundle install
        working-directory: ./my-resume

      # Шаг 5: Сборка сайта
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build
        working-directory: ./my-resume

      # Шаг 6: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-resume/_site
